var config = [
    { group: '', groupName: '', key: 'id', title: 'ID', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: 'emp', groupName: '用户', key: 'name', title: '用户姓名', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '是', displayInAdd: '', max: '30', min: '' },
    { group: '', groupName: '', key: 'code', title: '编码', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '30', min: '' },
    { group: '', groupName: '', key: 'password', title: '密码', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '20', min: '' },
    { group: '', groupName: '', key: 'gender', title: '性别', formType: '单选框', dataType: 'int', default: '0', options: '0:保密，1:男，2:女', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'account', title: '账号', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '30', min: '' },
    { group: '', groupName: '', key: 'email', title: '邮箱', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '100', min: '' },
    { group: '', groupName: '', key: 'fax', title: '传真', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '100', min: '' },
    { group: '', groupName: '', key: 'position', title: '职务', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'birthday', title: '出生日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD', min: '' },
    { group: '', groupName: '', key: 'deptId', title: '部门ID', formType: '', dataType: '', default: '', options: 'dynamic ', displayInTab: '否', displayInQuery: '是', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'roleId', title: '角色ID', formType: '', dataType: '', default: '', options: 'dynamic ', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'creatorId', title: '创建者ID', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'phone', title: '电话', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '20', min: '' },
    { group: '', groupName: '', key: 'description', title: '备注', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '100', min: '' },
    { group: '', groupName: '', key: 'IsLeader', title: '是否是企业负责人', formType: '单选框', dataType: 'int', default: '', options: '0:否,1:是', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'IsDeptManager', title: '是否是部门负责人', formType: '单选框', dataType: 'int', default: '', options: '0:否,1:是', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'sort', title: '排序', formType: '', dataType: 'int', default: '1', options: '1-99', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '99', min: '1' },
    { group: '', groupName: '', key: 'updateBy', title: '更新人ID', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'updateDate', title: '更新时间', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: 'YYYY-MM-DD HH:mm:ss', min: '' },
    { group: '', groupName: '', key: 'createDate', title: '创建时间', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: 'YYYY-MM-DD HH:mm:ss', min: '' },
    { group: '', groupName: '', key: 'status', title: '状态', formType: '开关', dataType: 'int', default: '1', options: '0:启用,1:禁用', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: 'role', groupName: '角色', key: 'name', title: '名称', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '是', displayInAdd: '', max: '30', min: '' },
    { group: '', groupName: '', key: 'permissionIds', title: '权限ID列表', formType: '', dataType: 'string[]', default: '', options: 'dynamic ', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'pageNum', title: '页码', formType: '', dataType: 'int', default: '1', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'pageSize', title: '每页的数量', formType: '', dataType: 'int', default: '10', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'idList', title: '角色id数组', formType: '', dataType: 'String[]', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: 'dept', groupName: '部门', key: 'name', title: '名称', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '是', displayInAdd: '', max: '30', min: '' },
    { group: '', groupName: '', key: 'parentId', title: '上级部门ID', formType: '', dataType: '', default: '', options: 'dynamic ', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '36', min: '' },
    { group: '', groupName: '', key: 'total', title: '总记录数', formType: '', dataType: 'int', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'size', title: '本页数量', formType: '', dataType: 'int', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'module', title: '模块名称', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'type', title: '日志类型', formType: '', dataType: '', default: '', options: 'ADD:新增,DELETE:删除,MODIFY:编辑,DISABLE:禁用,ENABLE:启用', displayInTab: '', displayInQuery: '是', displayInAdd: '否', max: '', min: '' },
    { group: 'log', groupName: '日志', key: 'date', title: '日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '是', displayInAdd: '否', max: 'YYYY-MM-DD', min: '' },
    { group: 'log', groupName: '日志', key: 'CONTENT', title: '接口参数', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'OPERATOR_NAME', title: '操作人', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '是', displayInAdd: '否', max: '30', min: '' },
    { group: 'leader', groupName: '企业负责人', key: 'name', title: '姓名', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '是', displayInAdd: '', max: '30', min: '' },
    { group: '', groupName: '', key: 'collectionNumber1', title: '托收协议1', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '36', min: '' },
    { group: '', groupName: '', key: 'collectionNumber2', title: '托收协议2', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '36', min: '' },
    { group: '', groupName: '', key: 'collectionNumber3', title: '托收协议3', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '36', min: '' },
    { group: '', groupName: '', key: 'collectionNumber4', title: '托收协议4', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '36', min: '' },
    { group: '', groupName: '', key: 'createById', title: '创建人ID', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '36', min: '' },
    { group: 'leader', groupName: '企业负责人', key: 'number', title: '工号', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '64', min: '' },
    { group: '', groupName: '', key: 'updateById', title: '更新人ID', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '否', max: '36', min: '' },
    { group: '', groupName: '', key: 'carConfigType', title: '用车类型', formType: '', dataType: '', default: '', options: 'dynamic ', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'effectiveDate', title: '生效日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD', min: '' },
    { group: '', groupName: '', key: 'leaveDate', title: '离职日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD', min: '' },
    { group: '', groupName: '', key: 'officeArea', title: '办公室面积', formType: '', dataType: 'float', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'trafficSubsidyPaymentStandard', title: '交通补贴发放标准', formType: '', dataType: 'float', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: 'car', groupName: '车辆', key: 'number', title: '车牌号', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '30', min: '' },
    { group: '', groupName: '', key: 'brand', title: '品牌', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'model', title: '型号', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'carTypeCode', title: '车辆类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic ', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'purposeCode', title: '车辆用途', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'configModeCode', title: '配置类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'useTypeCode', title: '使用类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'fundsSourceCode', title: '资金来源', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'displacementCode', title: '排量', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'accountBooksCode', title: '账簿', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'carTypeCode', title: '车辆类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic ', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'purposeValue', title: '车辆用途', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'configModeValue', title: '配置类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'useTypeValue', title: '使用类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'fundsSourceValue', title: '资金来源', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'displacementValue', title: '排量', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'accountBooksValue', title: '账簿', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'isWithinBudget', title: '是否预算内购车', formType: '单选框', dataType: 'int', default: '0', options: '0:否,1:是', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'purchaseDate', title: '购置日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD', min: '' },
    { group: '', groupName: '', key: 'purchaseTotalPrice', title: '购置总价', formType: '', dataType: 'Float', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'purchaseTax', title: '购置税', formType: '', dataType: 'Float', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'purchasePrice', title: '购置单价', formType: '', dataType: 'Float', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'managingRelationshipsCode', title: '管理关系', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'managingRelationshipsValue', title: '管理关系', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'propertyUnit', title: '产权单位', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '30', min: '' },
    { group: '', groupName: '', key: 'purchaseApplyDateAndDocumentNumber', title: '购置申请日期及文号', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '50', min: '' },
    { group: '', groupName: '', key: 'applicationReplyDateAndDocumentNumber', title: '批复日期及文号', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '50', min: '' },
    { group: '', groupName: '', key: 'driverId', title: '驾驶员id', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'etcId', title: 'ETCid', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'gasolineCardId', title: '油卡ID', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'disposalTypeCode', title: '处置类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'disposalTypeValue', title: '处置类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'disposer', title: '处置人', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '30', min: '' },
    { group: '', groupName: '', key: 'disposalDate', title: '处置日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD', min: '' },
    { group: '', groupName: '', key: 'scrapApprovalInfomation', title: '报废审批信息', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '100', min: '' },
    { group: '', groupName: '', key: 'dateOfBirth', title: '出生日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD', min: '' },
    { group: '', groupName: '', key: 'identityCardNumber', title: '身份证号', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '20', min: '' },
    { group: '', groupName: '', key: 'createById', title: '创建人ID', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '36', min: '' },
    { group: '', groupName: '', key: 'politicalOutlook', title: '政治面貌', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '36', min: '' },
    { group: '', groupName: '', key: 'nationality', title: '民族', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '36', min: '' },
    { group: '', groupName: '', key: 'educationDegree', title: '文化程度', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '64', min: '' },
    { group: '', groupName: '', key: 'unitBelongs', title: '所属单位', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '64', min: '' },
    { group: '', groupName: '', key: 'remarks', title: '备注', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '100', min: '' },
    { group: 'driver', groupName: '驾驶员', key: 'name', title: '姓名', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '是', displayInAdd: '', max: '64', min: '' },
    { group: '', groupName: '', key: 'updateById', title: '更新人ID', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '36', min: '' },
    { group: '', groupName: '', key: 'createByName', title: '创建人', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '否', max: '64', min: '' },
    { group: '', groupName: '', key: 'deptName', title: '部门名称', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '64', min: '' },
    { group: '', groupName: '', key: 'leaderName', title: '企业负责人', formType: '', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '64', min: '' },
    { group: '', groupName: '', key: 'leaderId', title: '企业负责人ID', formType: '', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '是', displayInAdd: '', max: '36', min: '' },
    { group: '', groupName: '', key: 'updateByName', title: '更新人', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '64', min: '' },
    { group: '', groupName: '', key: 'etcNumber', title: 'ETC卡号', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'gasolineNumber', title: '油卡卡号', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: 'etc', groupName: 'ETC', key: 'number', title: '卡号', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '36', min: '' },
    { group: '', groupName: '', key: 'operator', title: '操作人', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '64', min: '' },
    { group: '', groupName: '', key: 'carId', title: '车辆ID', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'carNumber', title: '车牌号', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: 'gasolineCard', groupName: '油卡', key: 'number', title: '卡号', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '36', min: '' },
    { group: '', groupName: '', key: 'gasolineCardTypeCode', title: '油卡类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'gasolineCardTypeValue', title: '油卡类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD', min: '' },
    { group: '', groupName: '', key: 'buyCardDate', title: '办卡日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'customerName', title: '客户名称', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '32', min: '' },
    { group: '', groupName: '', key: 'customerCode', title: '客户编号', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '36', min: '' },
    { group: '', groupName: '', key: 'dispatchTheme', title: '派车单主题', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '100', min: '' },
    { group: '', groupName: '', key: 'dispatchNumber', title: '派车单编号', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '64', min: '' },
    { group: '', groupName: '', key: 'dispatchTypeCode', title: '派车单类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'dispatchTypeValue', title: '派车单类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'mainPassenger', title: '主要乘车人', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '30', min: '' },
    { group: '', groupName: '', key: 'reason', title: '事由', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '100', min: '' },
    { group: '', groupName: '', key: 'passengersNumber', title: '乘客数量', formType: '', dataType: 'int', default: '', options: '0-99', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'reasonDescription', title: '事由简述', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '150', min: '' },
    { group: '', groupName: '', key: 'startTime', title: '开始时间', formType: '时间选择框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD HH:mm:ss', min: '' },
    { group: '', groupName: '', key: 'endTime', title: '结束时间', formType: '时间选择框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD HH:mm:ss', min: '' },
    { group: '', groupName: '', key: 'start', title: '起点', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '20', min: '' },
    { group: '', groupName: '', key: 'end', title: '终点', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '20', min: '' },
    { group: '', groupName: '', key: 'route', title: '途经', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '20', min: '' },
    { group: '', groupName: '', key: 'mileage', title: '里程数', formType: '', dataType: 'float', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'specialNeeds', title: '特殊需求', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '50', min: '' },
    { group: '', groupName: '', key: 'applyEmp', title: '申请人', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '32', min: '' },
    { group: '', groupName: '', key: 'applyDept', title: '申请部门', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '32', min: '' },
    { group: '', groupName: '', key: 'applyTime', title: '申请时间', formType: '时间选择框', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD HH:mm:ss', min: '' },
    { group: '', groupName: '', key: 'deptApproval', title: '部门审批人', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '32', min: '' },
    { group: '', groupName: '', key: 'deptApprovalComments', title: '部门审批意见', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '100', min: '' },
    { group: '', groupName: '', key: 'deptApprovalTime', title: '部门审批时间', formType: '时间选择框', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD HH:mm:ss', min: '' },
    { group: '', groupName: '', key: 'officeImplementer', title: '办公室落实人', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '32', min: '' },
    { group: '', groupName: '', key: 'officeImplementComments', title: '办公室落实意见', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '100', min: '' },
    { group: '', groupName: '', key: 'officeImplementTime', title: '办公室落实时间', formType: '时间选择框', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD HH:mm:ss', min: '' },
    { group: '', groupName: '', key: 'driverName', title: '驾驶员', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'amount', title: '金额', formType: '', dataType: 'float', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'documentNumber', title: '凭证号', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '30', min: '' },
    { group: '', groupName: '', key: 'financialSystemNumber', title: '财务系统/资金平台单号', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'entryDate', title: '入账日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '是', displayInAdd: '', max: 'YYYY-MM-DD', min: '' },
    { group: '', groupName: '', key: 'trainingTypeCode', title: '培训类型', formType: '下拉框', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: '', groupName: '', key: 'trainingTypeValue', title: '培训类型', formType: '下拉框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'trainingUnit', title: '培训单位', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '32', min: '' },
    { group: '', groupName: '', key: 'trainingProgram', title: '培训项目', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '50', min: '' },
    { group: '', groupName: '', key: 'trainingStartDate', title: '培训开始日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD', min: '' },
    { group: '', groupName: '', key: 'trainingEndDate', title: '培训结束日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD', min: '' },
    { group: '', groupName: '', key: 'trainingDays', title: '培训天数', formType: '', dataType: 'int', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'approvalBasis', title: '审批依据', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '100', min: '' },
    { group: '', groupName: '', key: 'isInPlan', title: '是否计划内培训', formType: '单选框', dataType: 'int', default: '', options: '0:否,1:是', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'reimbursementDate', title: '报销日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'travelDate', title: '出差日期', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '30', min: '' },
    { group: '', groupName: '', key: 'destination', title: '目的地', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '15', min: '' },
    { group: '', groupName: '', key: 'title', title: '摘要', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '100', min: '' },
    { group: '', groupName: '', key: 'amountWithoutTax', title: '不含税金额', formType: '', dataType: 'float', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'tax', title: '税额', formType: '', dataType: 'float', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'referenceInformation', title: '参考信息', formType: '', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '100', min: '' },
    { group: '', groupName: '', key: 'paymentTypeCode', title: '支付类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'paymentTypeValue', title: '支付类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'submitDate', title: '提交日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD', min: '' },
    { group: '', groupName: '', key: 'communicationTypeCode', title: '通讯类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'communicationTypeValue', title: '通讯类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: 'communication', groupName: '通讯费', key: 'date', title: '发生日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD', min: '' },
    { group: 'alcohol', groupName: '酒水', key: 'name', title: '名称', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: 'alcohol', groupName: '酒水', key: 'brand', title: '品牌', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'price', title: '单价', formType: '', dataType: 'float', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: 'entertainment', groupName: '招待费', key: 'number', title: '编号', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '36', min: '' },
    { group: 'entertainment', groupName: '招待费', key: 'date', title: '用餐日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD', min: '' },
    { group: '', groupName: '', key: 'entertainmentTypeCode', title: '招待类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'entertainmentTypeValue', title: '招待类型', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: 'entertainment', groupName: '招待费', key: 'reason', title: '招待事由', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'applyDeptName', title: '申请部门', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'applyDeptId', title: '申请部门Id', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'applyEmpName', title: '申请人', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'applyEmpId', title: '申请人ID', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'alcoholAmount', title: '酒水金额', formType: '', dataType: 'float', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'reimbursementAmount', title: '报销金额', formType: '', dataType: 'float', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'guestNumber', title: '来宾人数', formType: '', dataType: 'int', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'accompanyNumber', title: '陪同人数', formType: '', dataType: 'int', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'totalNumber', title: '总人数', formType: '', dataType: 'int', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'average', title: '人均', formType: '', dataType: 'float', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'entertainmentNatureCode', title: '招待性质', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'entertainmentNatureValue', title: '招待性质', formType: '下拉框', dataType: '', default: '', options: 'dynamic', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'standard', title: '人均标准', formType: '', dataType: 'float', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'mainUnitName', title: '主体单位', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'activityOrganizationUnit', title: '活动组织单位', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'projectName', title: '考察项目名称', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'destination', title: '考察目的地', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: 'abroad', groupName: '因公临时出国', key: 'date', title: '考察日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: 'YYYY-MM-DD', min: '' },
    { group: '', groupName: '', key: 'actualExpenses', title: '实际花费', formType: '', dataType: 'float', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: '', groupName: '', key: 'daysNumber', title: '天数', formType: '', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: 'abroad', groupName: '因公临时出国', key: 'isInPlan', title: '是否计划内考察', formType: '单选框', dataType: 'int', default: '', options: '0:否,1:是', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: 'operation', groupName: '运行费', key: 'date', title: '日期', formType: '日期选择框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },
    { group: 'operation', groupName: '运行费', key: 'operationPaymentTypeCode', title: '支付类型', formType: '下拉框', dataType: '', default: '', options: '', displayInTab: '否', displayInQuery: '', displayInAdd: '否', max: '', min: '' },
    { group: 'operation', groupName: '运行费', key: 'operationPaymentTypeValue', title: '支付类型', formType: '下拉框', dataType: '', default: '', options: '', displayInTab: '', displayInQuery: '', displayInAdd: '', max: '', min: '' },

]

utTrim = str => (str || '').replace(/^\s+|\s+$/g, '')

config.forEach(d => {
    Object.keys(d).forEach(k => {
        d[k] = (d[k] === 0 ? '0' : d[k]) || ''
        let v = d[k]
        switch (k) {
            case 'options':
                if (v) {
                    let arr = v.split(v.indexOf('，') !== -1 ? '，' : ',')
                    let res = arr.map(dd => {
                        let str = utTrim(dd)
                        if (str === 'dynamic') return str
                        if (str === '0-99') {
                            d.min = '0'
                            d.max = '99'
                            return ''
                        }
                        return { label: utTrim(str.split(':')[0]), value: utTrim(str.split(':')[1]) }
                    })
                    d[k] = String(res) === 'dynamic' ? 'dynamic' : res
                }
                break
            case 'formType':
                // 为空则默认 输入框'input'
                d[k] = { '单选框': 'radio', '开关': 'switch', '日期选择框': 'datepicker', '时间选择框': 'timepicker', '下拉框': 'select'}[v] || 'input'
                break
            case 'max': 
                if (v.startsWith('YYYY')) {
                    d.format = v
                    d[k] = ''
                }
                break
            default:
                if (v === '是') d[k] = 'y'
                else if (v === '否') d[k] = 'n'
        }
        if (d[k] === '') delete d[k]
    })
})
config.sort((a, b) => a.key.toLowerCase() > b.key.toLowerCase() ? 1 : -1)
console.log(config)